sudo: false

services:
  - docker

cache:
  directories:
    - elm-stuff/build-artifacts
    - test/elm-stuff/build-artifacts
    - sysconfcpus
    - $HOME/.nvm
os:
  - linux

env:
  - ELM_VERSION=0.18.0
  - TARGET_NODE_VERSION=node

install:
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - node --version
  - npm --version
  - npm install -g elm@$ELM_VERSION
  - npm install

script:
  - npm run-script build
  - npm run-script test

notifications:
  slack: kindlyops:YkyQcYjU04mC2JTN1orHBDCs
