version: '2'
services:
  tellform:
      image: tellform/production:no_subdomains
      environment:
        - REDIS_URL=redis://redis-db:6379
        - MONGODB_URI=mongodb://mongo-db:27017/mean
        - CREATE_ADMIN_ACCOUNT=TRUE
        - SUBDOMAINS_DISABLED=TRUE
        - BASE_URL=localhost
        - SOCKET_URL=localhost
        - SOCKET_PORT=5555
      links:
        - redis:redis-db
        - mongo:mongo-db
      ports:
        - "3000:3000"
        - "5555:5555"
  mongo:
      image: mongo
      ports:
        - "27017:27017"
  redis:
      image: redis
      ports:
        - "6379:6379"
  keycloak:
    image: jboss/keycloak-postgres
    environment:
      - POSTGRES_DATABASE=mappamundi_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT_5432_TCP_ADDR=postgres
    volumes:
      - ./keycloak/keycloak-add-user.json:/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json
    ports:
      - "8080:8080"
    links:
      - db:postgres
  sqitch:
    build:
      context: .
    working_dir: /src
    volumes:
      - .:/src
    links:
      - db
  api:
    image: begriffs/postgrest:v0.3.2.0
    command: [postgrest, "postgres://postgres@db/mappamundi_dev", --jwt-secret, "${POSTGREST_JWT_SECRET}", -a, postgres, --schema, "1"]
    ports:
      - "3001:3000"
    links:
      - db
    env_file: .env
  db:
    image: postgres:9.5
    ports:
      - "5434:5432"
  webui:
    working_dir: /code
    volumes:
      - ./web:/code
      - /code/node_modules
    build:
      context: .
      dockerfile: ./web/Dockerfile-hotreload
    links:
      - api
    ports:
      - "2015:2015"
    command: [/code/installrun.sh]
  marketing:
    volumes:
      - ./marketing/public:/public
    build:
      context: .
      dockerfile: ./marketing/Dockerfile
    ports:
      - "5000:2015"
