---
version: '2'

services:
  zap:
    image: owasp/zap2docker-weekly
    depends_on:
      - webui
    command: zap-baseline.py -t http://webui:2016
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - "./alertmanager/:/etc/alertmanager/"
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
  # 
  # cadvisor is not working on windows, remove for now
  #
  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - ./prometheus/:/etc/prometheus/
  #     - prometheus_data:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.console.libraries=/usr/share/prometheus/console_libraries'
  #     - '--web.console.templates=/usr/share/prometheus/consoles'
  #   ports:
  #     - 9090:9090
  #   depends_on:
  #     - cadvisor
  # cadvisor:
  #   image: google/cadvisor
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #  ports:
  #    - 8080:8080
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/maildir
      - VIRTUAL_HOST=mailhog.dev.havengrc.com
      - VIRTUAL_PORT=8025
    volumes:
      - ./mailhog/maildir:/maildir
  apitest:
    build:
      context: ./apitest
      dockerfile: ./apitest/Dockerfile
    working_dir: /usr/src/app
    environment:
      - AUTH_SERVER=dev.havengrc.com
      - BUFFALO_SERVER=dev.havengrc.com
    volumes:
      - ./apitest:/usr/src/app
    links:
      - keycloak
      - webui:dev.havengrc.com
    depends_on:
      - start_dependencies
    command: [cucumber]
  swagger:
    image: havengrc-docker.jfrog.io/swaggerapi/swagger-ui:v3.0.2
    ports:
      - "3002:8080"
    volumes:
      - ./swagger/index.html:/usr/share/nginx/html/index.html
  unleash:
    build:
      context: ./unleash
    ports:
      - "4242:4242"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/mappamundi_dev
      - KEYCLOAK_HOST=http://localhost:2015
      - KEYCLOAK_REALM=havendev
      - KEYCLOAK_CLIENT_ID=unleash
      - KEYCLOAK_CLIENT_SECRET=2e78e079-b39a-4a8b-8f33-0ab327518ae6
      - SITE_URL=http://localhost:2015/unleash
    depends_on:
      - start_dependencies
    links:
      - keycloak
  # grafana:
  #   image: grafana/grafana
  #   depends_on:
  #     - prometheus
  #   ports:
  #     - 3500:3000
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #     - ./grafana/provisioning/:/etc/grafana/provisioning/
  #   env_file:
  #     - ./grafana/config.monitoring
  docs:
    working_dir: /docs
    volumes:
      - ./docs:/docs
      - /docs/node_modules
    build:
      context: .
      dockerfile: ./docs/Dockerfile
    ports:
      - "4000:4000"
    command: [serve]
    environment:
      - VIRTUAL_HOST=docs.dev.havengrc.com
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - "PGADMIN_DEFAULT_EMAIL=user1@havengrc.com"
      - "PGADMIN_DEFAULT_PASSWORD=password"
    ports:
      - "8081:80"
    volumes:
      - ./postgresql-data/servers.json:/pgadmin4/servers.json
  plantuml:
    working_dir: /docs
    volumes:
      - ./docs:/docs
    build:
      context: .
      dockerfile: ./docs/plantuml/Dockerfile
    command: [-v, /docs/plantuml/*.puml]
  mjml:
    build:
      context: mjml/
    volumes:
      - ./mjml/templates:/home/mjml/templates
      - ./mjml/dist:/home/mjml/dist
    command: ["templates/*.mjml", "-o", "dist/"]
  cypress:
    build:
      context: webui
      dockerfile: Dockerfile-cypress
    depends_on:
      - gatekeeper
    volumes:
      - ./webui:/e2e
    extra_hosts:
      - "dev.havengrc.com:127.0.0.1"
    environment:
      - "GATEKEEPER_INTERNAL=http://gatekeeper:81"
