version: '2'
services:
  sqitch:
    build: .
    working_dir: /src
    volumes:
      - .:/src
    links:
      - db
    command: "/bin/true"
  api:
    image: begriffs/postgrest:v0.3.2.0
    command: [postgrest, "postgres://postgres@db/mappamundi_dev", "--jwt-secret=$JWT_SECRET", -a, postgres, --schema, "1"]
    ports:
      - "3000:3000"
    links:
      - db
    env_file: .env
  db:
    image: postgres:9.5
