version: '2'
services:
  sqitch:
    build:
      context: .
    working_dir: /src
    volumes:
      - .:/src
    links:
      - db
  api:
    image: begriffs/postgrest:v0.3.2.0
    command: [postgrest, "postgres://postgres@db/mappamundi_dev", --jwt-secret, "${POSTGREST_JWT_SECRET}", -a, postgres, --schema, "1"]
    ports:
      - "3000:3000"
    links:
      - db
    env_file: .env
  db:
    image: postgres:9.5
    ports:
      - "5434:5432"
  webui:
    working_dir: /code
    volumes:
      - ./web:/code
      - /code/node_modules
    build:
      context: .
      dockerfile: ./web/Dockerfile-hotreload
    links:
      - api
    ports:
      - "2015:2015"
    command: [/code/installrun.sh]
  marketing:
    volumes:
      - ./marketing/public:/public
    build:
      context: .
      dockerfile: ./marketing/Dockerfile
    ports:
      - "8080:2015"
