version: '2'
services:
  sqitch:
    build:
      context: .
    working_dir: /src
    volumes:
      - .:/src
    links:
      - db
  api:
    image: begriffs/postgrest:v0.3.2.0
    command: [postgrest, "postgres://postgres@db/mappamundi_dev", --jwt-secret, "${POSTGREST_JWT_SECRET}", -a, postgres, --schema, "1"]
    ports:
      - "3000:3000"
    links:
      - db
    env_file: .env
  db:
    image: postgres:9.5
    ports:
      - "5434:5432"
  webui:
    working_dir: /code
    volumes:
      - ./web:/code
      - /code/node_modules
    build:
      context: .
      dockerfile: ./web/Dockerfile-hotreload
    links:
      - api
    ports:
      - "2015:2015"
    command: [/code/installrun.sh]
  tellform:
      image: tellform/development
      environment:
        - REDIS_URL=redis://redis-db:6379
        - DB_HOST=db
      links:
        - redis:redis-db
        - mongo:db
      ports:
        - "4000:3000"
  mongo:
      image: mongo
      ports:
        - "27017:27017"
  redis:
      image: redis
      ports:
        - "6379:6379"
  marketing:
    volumes:
      - ./marketing/public:/public
    build:
      context: .
      dockerfile: ./marketing/Dockerfile
    ports:
      - "8080:2015"
