version: '2'
services:
  sqitch:
    image: kindlyops/sqitch:pgsql
    working_dir: /code
    volumes:
      - .:/code
    links:
      - db
    command: "/bin/true"
  api:
    image: begriffs/postgrest:v0.3.2.0
    command: [postgrest, "postgres://postgres@db/mappamundi_dev", -a, postgres, --schema, "1"]
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: postgres:9.5
