version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Check docker compose version
          command: docker-compose -v
      - run:
          name: Build images
          command: docker-compose build
      - restore_cache:
          key: sysconfcpus
      - run:
          name: Install sysconfcpus
          command: |
            if [ ! -d sysconfcpus/bin ];
            then
              git clone https://github.com/obmarg/libsysconfcpus.git;
              cd libsysconfcpus;
              ./configure --prefix="$HOME/$CIRCLE_PROJECT_REPONAME/sysconfcpus";
              make && make install;
              cd ..;
            fi
      - run:
          name: Install Elm system with npm
          command: npm install --only=dev
          no_output_timeout: 15m
          working_directory: webui
      - run:
          name: Install OpenShift client
          command: |
            wget https://github.com/openshift/origin/releases/download/v3.7.0/openshift-origin-client-tools-v3.7.0-7ed6862-linux-64bit.tar.gz
            tar xvzf openshift-origin-client-tools-v3.7.0-7ed6862-linux-64bit.tar.gz
            sudo mv openshift-origin-client-tools-v3.7.0-7ed6862-linux-64bit/oc /usr/local/bin/oc
            oc version
            # todo: authenticate
            oc login https://console.pro-us-east-1.openshift.com/ --token=$OPENSHIFT_TOKEN
            oc project haven-production
      - run: docker-compose run start_dependencies
      - run: docker-compose run sqitch
      - run: docker-compose run start_keycloak
      - run: docker build --rm=false -t kindlyops/mappamundi .
      - run: docker build --rm=false -t kindlyops/havenapi havenapi/
      - run:
          name: compile Elm project
          command: npm run-script build
          no_output_timeout: 15m
          working_directory: webui
      - run: docker build --rm=false -t kindlyops/havenweb webui
      - run: ./test
      - deploy:
          name: Prerelease
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag kindlyops/mappamundi kindlyops/mappamundi:$CIRCLE_SHA1
              docker tag kindlyops/havensqitch kindlyops/havensqitch:$CIRCLE_SHA1
              docker tag kindlyops/havensqitch kindlyops/havensqitch:latest
              docker tag kindlyops/havenweb kindlyops/havenweb:$CIRCLE_SHA1
              docker tag kindlyops/havenweb kindlyops/havenweb:latest
              docker push kindlyops/mappamundi:$CIRCLE_SHA1
              docker push kindlyops/havensqitch:$CIRCLE_SHA1
              docker push kindlyops/havensqitch:latest
              docker push kindlyops/havenweb:$CIRCLE_SHA1
              docker push kindlyops/havenweb:latest
              oc import-image havenweb --from=docker.io/kindlyops/havenweb:latest
              oc import-image havensqitch --from=docker.io/kindlyops/havensqitch:latest
            else
              echo "Not master branch so not deploying"
            fi
      # TODO: port to circle 2.0
      # release:
      #   tag: /v[0-9]+(\.[0-9]+)*/
      #   owner: kindlyops
      #   commands:
      #     - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      #     - docker tag kindlyops/mappamundi kindlyops/mappamundi:$CIRCLE_TAG
      #     - docker tag kindlyops/havenweb kindlyops/havenweb:$CIRCLE_TAG
      #     - docker tag kindlyops/mappamundi kindlyops/mappamundi:$CIRCLE_SHA1
      #     - docker tag kindlyops/havenweb kindlyops/havenweb:$CIRCLE_SHA1
      #     - docker push kindlyops/mappamundi:$CIRCLE_TAG
      #     - docker push kindlyops/havenweb:$CIRCLE_TAG
      #     - docker push kindlyops/mappamundi:$CIRCLE_SHA1
      #     - docker push kindlyops/havenweb:$CIRCLE_SHA1
