AWSTemplateFormatVersion: '2010-09-09'
Resources:
  havenwebDNS:
    Type: "AWS::Route53::RecordSet"
    Properties:
      AliasTarget: a078408a9197511e7b52f0238925a1fb-1279596815.us-west-2.elb.amazonaws.com
      Comment: Haven webui ELB loadbalancer for k8s. Fails with Value of property AliasTarget must be an object
      HostedZoneName: havengrc.com
      Name: app.havengrc.com.
      Type: A
