---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: db
  creationTimestamp:
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp:
      labels:
        service: db
    spec:
      containers:
      - name: db
        image: postgres
        resources: {}
      restartPolicy: Always
  strategy: {}
status: {}
