---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: havenweb
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        service: havenweb
    spec:
      containers:
        - name: havenweb
          image: havengrc-docker.jfrog.io/kindlyops/havenweb:latest
          env:
            - name: FEATURE_ENV
              value: "production"
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 80
              initialDelaySeconds: 5
              periodSeconds: 5
              successThreshold: 1
          volumeMounts:
            - name: secret-volume
              mountPath: /certs/
              readOnly: true
          resources:
              limits:
                memory: 128Mi
              requests:
                memory: 128Mi
      volumes:
        - name: secret-volume
          secret:
            secretName: haven-tls
      restartPolicy: Always
  strategy:
    type: "Recreate"
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0
status: {}
