---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        service: keycloak
    spec:
      containers:
        - name: keycloak
          image: havengrc-docker.jfrog.io/kindlyops/keycloak:latest
          env:
            - name: DB_DATABASE
              value: "havenstage"
            - name: KEYCLOAK_HOSTNAME
              value: "www.havengrc.com"
            - name: KEYCLOAK_HTTP_PORT
              value: "80"
            - name: KEYCLOAK_HTTPS_PORT
              value: "443"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: haven-database-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: haven-database-credentials
                  key: password
            - name: DB_ADDR
              value: "db"
            - name: KEYCLOAK_USER
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: haven-database-credentials
                  key: password
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 764Mi
            requests:
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 5
      restartPolicy: Always
  strategy:
    type: "Recreate"
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0
status: {}
