---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        service: keycloak
    spec:
      containers:
        - name: keycloak
          image: havengrc-docker.jfrog.io/kindlyops/keycloak:3.4.2.Final.2
          env:
            - name: POSTGRES_DATABASE
              value: "havenstage"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: haven-database-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: haven-database-credentials
                  key: password
            - name: POSTGRES_PORT_5432_TCP_ADDR
              value: "db"
            - name: KEYCLOAK_USER
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: haven-database-credentials
                  key: password
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
          ports:
            - containerPort: 8443
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8443
            initialDelaySeconds: 30
            periodSeconds: 5
      restartPolicy: Always
  strategy:
    type: "Recreate"
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0
status: {}
