---
apiVersion: batch/v1
kind: Job
metadata:
  name: sqitch-migrate
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: sqitch-migrate
    spec:
      containers:
      - name: sqitch-migrate
        image: kindlyops/havensqitch:latest
        command:
          - "/usr/local/bin/run-sqitch.sh"
          - "deploy"
        env:
          - name: DATABASE_NAME
            value: "havenstage"
          - name: DATABASE_HOST
            value: "db"
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: haven-database-credentials
                key: username
          - name: SQITCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: haven-database-credentials
                key: password
      restartPolicy: Never
